pom.xml

Added the Apache Snapshots repo to make sure Sling snapshots are found. Build should now work without any other changes.

LFS-1: Set up a build system

---

distribution/src/main/provisioning/50-lfs.txt
modules/ui-extension/pom.xml
modules/ui-extension/src/main/resources/SLING-INF/nodetypes/extension.cnd

LFS-73: Add a nodetype for UI Extension

---

modules/commons/src/main/frontend/package.json
modules/commons/src/main/frontend/webpack.config.js
modules/data-entry/src/main/frontend/package.json
modules/data-entry/src/main/frontend/webpack.config.js
modules/homepage/src/main/frontend/package.json
modules/homepage/src/main/frontend/webpack.config.js

- Removing unneeded dependencies from package.json and webpack.config.js in the data-entry and homepage modules
- updating package versions
- adding missing details

LFS-53: Clean up the npm and webpack configuration files

---

modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd

In `modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd`.

LFS-98: Add a new answer type: VocabularyAnswer

---

modules/ui-extension/pom.xml
modules/ui-extension/src/main/resources/SLING-INF/content/libs/lfs/Extension/null.GET.esp
modules/ui-extension/src/main/resources/SLING-INF/content/libs/lfs/ExtensionPoint/null.GET.esp
modules/ui-extension/src/main/resources/SLING-INF/content/libs/lfs/ExtensionPoint/resolved.html

Also includes LFS-75 which should be merged first.

LFS-71 / LFS-77: Add a default rendering script for resources of type lfs/ExtensionPoint

---

modules/thesaurus/src/main/frontend/src/query/browse.jsx
modules/thesaurus/src/main/frontend/src/query/browseListChild.jsx
modules/thesaurus/src/main/frontend/src/query/browseStyle.jsx
modules/thesaurus/src/main/frontend/src/query/query.jsx
modules/thesaurus/src/main/frontend/src/query/queryStyle.jsx
modules/thesaurus/src/main/frontend/src/query/util.jsx

Redoing PR #48 into LFS-44 so that the comparison is easier to read.

LFS-105: UI to browse NCI Thesaurus terms as a tree

---

modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx

Fixing an inability to add custom text when the input is checkboxes (from PR #77 ).

[misc] Fix behaviour of multiple choice input with custom text

---

modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
modules/data-entry/src/main/frontend/src/questionnaire/TextQuestion.jsx
modules/data-entry/src/main/frontend/webpack.config.js

Test rig this time:
`modules/data-entry/src/main/frontend/webpack.config.js` line 19:
```
[module_name + 'testRig']: './src/questionnaire/testRig.jsx'
```
`modules/data-entry/src/main/frontend/src/questionnaire/testRig.jsx` line 19:
```
//
//  Licensed to the Apache Software Foundation (ASF) under one
//  or more contributor license agreements.  See the NOTICE file
//  distributed with this work for additional information
//  regarding copyright ownership.  The ASF licenses this file
//  to you under the Apache License, Version 2.0 (the
//  "License"); you may not use this file except in compliance
//  with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing,
//  software …
```

LFS-116: As a user, I can select simple text options as answers to questions 

---

modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
modules/data-entry/src/main/frontend/src/questionnaire/BooleanQuestion.jsx
modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
modules/data-entry/src/main/frontend/webpack.config.js

Test rig this time:
`modules/data-entry/src/main/frontend/webpack.config.js` line 19:
```
[module_name + 'testRig']: './src/questionnaire/testRig.jsx'
```
`modules/data-entry/src/main/frontend/src/questionnaire/testRig.jsx` line 19:
```
//
//  Licensed to the Apache Software Foundation (ASF) under one
//  or more contributor license agreements.  See the NOTICE file
//  distributed with this work for additional information
//  regarding copyright ownership.  The ASF licenses this file
//  to you under the Apache License, Version 2.0 (the
//  "License"); you may not use this file except in compliance
//  with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing,
//  software …
```

LFS-118: As a user, I can select Yes/No/Unknown as answers to questions

---

modules/data-entry/src/main/frontend/package.json
modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
modules/data-entry/src/main/frontend/webpack.config.js

Test rig this time:
`modules/data-entry/src/main/frontend/webpack.config.js` line 19:
```
[module_name + 'testRig']: './src/questionnaire/testRig.jsx'
```
`modules/data-entry/src/main/frontend/src/questionnaire/testRig.jsx` line 19:
```
//
//  Licensed to the Apache Software Foundation (ASF) under one
//  or more contributor license agreements.  See the NOTICE file
//  distributed with this work for additional information
//  regarding copyright ownership.  The ASF licenses this file
//  to you under the Apache License, Version 2.0 (the
//  "License"); you may not use this file except in compliance
//  with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing,
//  software …
```

LFS-117: As a user, I can select numbers as answers to questions

---

modules/data-entry/src/main/frontend/package.json
modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
modules/data-entry/src/main/frontend/src/dataHomepage/LiveTable.jsx
modules/data-entry/src/main/frontend/src/dataHomepage/Questionnaires.jsx
modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
modules/data-entry/src/main/frontend/webpack.config.js

This is a draft PR, more of a proof of concept. UI looks very basic.

LFS-163: As an administrator, I can see details about a Questionnaire

---

modules/data-entry/src/main/frontend/package.json
modules/data-entry/src/main/frontend/src/dataHomepage/Forms.jsx
modules/data-entry/src/main/frontend/src/questionnaire/Answer.jsx
modules/data-entry/src/main/frontend/src/questionnaire/AnswerComponentManager.jsx
modules/data-entry/src/main/frontend/src/questionnaire/BooleanQuestion.jsx
modules/data-entry/src/main/frontend/src/questionnaire/DateQuestion.jsx
modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx
modules/data-entry/src/main/frontend/src/questionnaire/NumberQuestion.jsx
modules/data-entry/src/main/frontend/src/questionnaire/PedigreeQuestion.jsx
modules/data-entry/src/main/frontend/src/questionnaire/Question.jsx
modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx
modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
modules/data-entry/src/main/frontend/src/questionnaire/TextQuestion.jsx
modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/DataImportServlet.java
modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd
questionnaires/clinical-data/src/main/resources/SLING-INF/content/Demographics.json

LFS-124 / LFS-181: Basic form display and saving functionality

---

README.md
distribution/Dockerfile
distribution/pom.xml

LFS-217: As an administrator, I can deploy the application using Docker

---

modules/data-entry/src/main/frontend/src/questionnaire/Form.jsx
modules/data-entry/src/main/frontend/src/questionnaire/Questionnaire.jsx

Fix an infinite loop caused if an error occurs while accessing form data.

LFS-221: Accessing a non-existing form hangs

---

modules/data-entry/src/main/frontend/src/questionnaire/DateQuestion.jsx

[Jira link](https://phenotips.atlassian.net/browse/LFS-230)
To test: create a new demographics form, and open the console. The warnings should be gone now.

LFS-230: Date questions give warnings on forms with multiple date questions

---

modules/homepage/src/main/frontend/src/themePage/Navbars/Navbar.jsx
modules/homepage/src/main/frontend/src/themePage/Navbars/headerStyle.jsx
modules/homepage/src/main/frontend/src/themePage/Sidebar/sidebar.jsx
modules/homepage/src/main/frontend/src/themePage/Sidebar/sidebarStyle.jsx
modules/homepage/src/main/frontend/src/themePage/index.jsx

Since the main content is not predictable, this places a skeleton UI only on the sidebar and top breadcrumb.

LFS-228: As a user, I can see a skeleton UI before the main content has loaded

---

modules/data-entry/src/main/frontend/src/dataHomepage/Filters.jsx
modules/data-entry/src/main/frontend/src/questionnaire/VocabularyQuestion.jsx
modules/data-entry/src/main/frontend/src/vocabQuery/query.jsx
modules/data-entry/src/main/frontend/src/vocabSelector/select.jsx
questionnaires/clinical-data/src/main/resources/SLING-INF/content/Demographics.json

[Jira link](https://phenotips.atlassian.net/browse/LFS-258)

LFS-258: Rename suggestionCategories to vocabularyFilter

---

modules/data-entry/src/main/frontend/src/questionnaire/MultipleChoice.jsx

Test branch: [LFS-257_LFS-265](https://github.com/ccmbioinfo/lfs/tree/LFS-257_LFS-265-test) -> Demographics data form -> questions _Patient ID,_ _Test multiple choice widget_ x2.

LFS-257 / LFS-265: The interaction with multiple select widgets with a user input is confusing

---

modules/data-entry/src/main/frontend/src/questionnaire/ConditionalGroup.jsx
modules/data-entry/src/main/frontend/src/questionnaire/FormEntry.jsx
modules/data-entry/src/main/frontend/src/questionnaire/QuestionnaireStyle.jsx
modules/data-entry/src/main/frontend/src/questionnaire/Section.jsx
modules/data-entry/src/main/resources/SLING-INF/nodetypes/dataentry.cnd

Draft PR until the UI gets finalized.
[Jira link](https://phenotips.atlassian.net/browse/LFS-243)
**Test branch**: `LFS-243-test`
This branch handles recurrent/repeatable sections, whose answers are stored individually.

LFS-243: As an administrator I can specify questionnaires with recurring sections/questions

---

modules/data-entry/src/main/java/ca/sickkids/ccm/lfs/PaginationServlet.java

LFS-325: Many empty rows displayed in the data tables
